#!/bin/sh

#Required programs
nsis_url="http://downloads.sourceforge.net/project/nsis/NSIS%202/2.46/nsis-2.46-setup.exe"
nsis_md5="5e02441c7f3fa4da4f4928a2d42a07c3"

p7zip_url="http://heanet.dl.sourceforge.net/sourceforge/sevenzip/7z464.exe"
p7zip_md5="d2810e3dd4b60ab05fe7c29a50921efa"

mfc42_url="http://download.microsoft.com/download/vc60pro/update/1/w9xnt4/en-us/vc6redistsetup_enu.exe"
mfc42_md5="dd50945bcf3e09e22453be43684f3d39"

enumini_url="http://nsis.sourceforge.net/mediawiki/images/6/62/EnumINI.zip"

root="$(cd ${0%/*}/../;pwd)"
export WINEPREFIX="$root"/wine

download(){
	wget  -P /tmp -O "$2" "$1"
	md5=$(md5sum $2)
	md5=${md5%% *}
	if [ ! "$md5" = "$3" ]; then
		echo "Invalid download for $1, md5 does not match"
		exit 1
	fi
}

install_nsis(){
	echo "Installing nsis..."
	download "$nsis_url" "/tmp/nsis.exe" "$nsis_md5"
	wine "/tmp/nsis.exe"
}

install_7z(){
	echo "Installing 7z..."
	download "$p7zip_url" "/tmp/p7zip.exe" "$p7zip_md5"
	wine "/tmp/p7zip.exe"
}

install_wine(){
	if [ ! -x /usr/bin/wine -a ! -x /usr/local/bin/wine ]; then
		echo "Installing wine..."
		sudo pacman -S --noconfirm wine #TBD do not assume apt
	fi
	#echo "Creating wine folder..."
	#wineprefixcreate --prefix "$WINEPREFIX"
}

install_zip(){
	if [ ! -x /usr/bin/zip -a ! -x /usr/local/bin/zip ]; then
		echo "Installing zip..."
		sudo pacman -S --noconfirm zip #TBD do not assume apt
	fi
}

install_unzip(){
	if [ ! -x /usr/bin/unzip -a ! -x /usr/local/bin/unzip ]; then
		echo "Installing unzip..."
		sudo pacman -S --noconfirm unzip #TBD do not assume apt
	fi
}

install_png2ico(){
	if [ ! -x /usr/bin/png2ico -a ! -x /usr/local/bin/png2ico ]; then
		echo "Installing png2ico..."
		sudo pacman -S --noconfirm png2ico #TBD do not assume apt
	fi
}

install_cabextract(){
	if [ ! -x /usr/bin/cabextract -a ! -x /usr/local/bin/cabextract ]; then
		echo "Installing cabextract..."
		sudo pacman -S --noconfirm cabextract #TBD do not assume apt
	fi
}

install_cert(){
	echo "Installing mfc42..."
	download "$mfc42_url" "/tmp/vc6redistsetup_enu.exe" "$mfc42_md5"
	wine "/tmp/vc6redistsetup_enu.exe" '/T:C:\winetrickstmp' /c
	mv $WINEPREFIX/dosdevices/c:/winetrickstmp/vcredist.exe /tmp
	rm -f $WINEPREFIX/dosdevices/c:/windows/system32/comcat.dll
	rm -f $WINEPREFIX/dosdevices/c:/windows/system32/msvcrt.dll
	rm -f $WINEPREFIX/dosdevices/c:/windows/system32/oleaut32.dll
	rm -f $WINEPREFIX/dosdevices/c:/windows/system32/olepro32.dll
	rm -f $WINEPREFIX/dosdevices/c:/windows/system32/stdole2.tlb
	wine /tmp/vcredist.exe
	/usr/bin/cabextract /tmp/vcredist.exe -d $WINEPREFIX/dosdevices/c:/windows/system32/ -F mfc42u.dll
	cat > /tmp/override-dll.reg <<EOF
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\DllOverrides]
"*msvcrt"="native,builtin"
EOF
	wine regedit "/tmp/override-dll.reg"
	rm /tmp/override-dll.reg
	rm -rf '$WINEPREFIX/dosdevices/c:/winetrickstmp/*'
}

make_wine(){
	install_wine
	install_nsis
	install_png2ico
	install_zip
	install_7z
	install_cabextract
	install_cert
}

if [ ! -e "$root/wine" ]; then
	make_wine
fi
	#install_cabextract
	#install_cert
